In [1]:
import pandas as pd

df = pd.read_csv('C:\\Users\\ncevik\\Desktop\\TÄ°K2\\Flight\\Data\\states_2021-12-06-23.csv') # Use Tab to separate
df

,time,icao24,lat,lon,velocity,heading,vertrate,callsign,onground,alert,spi,squawk,baroaltitude,geoaltitude,lastposupdate,lastcontact
0,1638831600,a48c07,53.370209,10.209516,238.707005,208.442929,0.00000,UPS291,False,False,False,3526.0,12199.62,11833.86,1.638832e+09,1.638832e+09
1,1638831600,ac2706,42.743271,-87.731823,189.596171,262.045786,-0.32512,UAL2375,False,False,False,3071.0,10980.42,10607.04,1.638832e+09,1.638832e+09
2,1638831600,34210d,52.829807,11.069667,140.857172,223.076059,0.00000,SWT2KR,False,False,False,1341.0,6713.22,6469.38,1.638832e+09,1.638832e+09
3,1638831610,43be94,50.902451,127.671432,184.966765,170.878252,-8.45312,SVR349,False,False,False,NaN,4305.30,4160.52,1.638832e+09,1.638832e+09
4,1638831610,a9c508,30.889737,-101.092236,240.784524,279.220824,0.00000,AAL1536,False,False,False,5711.0,10972.80,11323.32,1.638830e+09,1.638832e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2131123,1638835190,ac20a1,NaN,NaN,NaN,NaN,NaN,SWA4706,False,False,False,NaN,NaN,NaN,NaN,1.638835e+09
2131124,1638835190,abef16,41.064288,-90.707307,268.043097,84.934997,-5.20192,SWA6258,False,False,False,617.0,7307.58,7178.04,1.638835e+09,1.638835e+09
2131125,1638835190,42498d,59.997781,48.072641,233.968543,70.608882,0.00000,AFL1512,False,False,False,NaN,10675.62,10195.56,1.638835e+09,1.638835e+09
2131126,1638835190,a7a60e,35.429718,-80.983601,113.319064,177.137595,-3.90144,JIA5310,False,False,False,6251.0,1485.90,1478.28,1.638835e+09,1.638835e+09
2131127,1638835190,abb9b2,37.268463,-95.272093,200.098217,251.565051,0.00000,SWA2317,False,False,False,2127.0,8534.40,8656.32,1.638835e+09,1.638835e+09

In [7]:
df.dtypes

time               int64
icao24            object
lat              float64
lon              float64
velocity         float64
heading          float64
vertrate         float64
callsign          object
onground            bool
alert               bool
spi                 bool
squawk           float64
baroaltitude     float64
geoaltitude      float64
lastposupdate    float64
lastcontact      float64
dtype: object

In [4]:
uniqueValues = (df['callsign']).unique()
len(uniqueValues)

10279